##########################################
# Program detects 3' ends of transcripts #
##########################################


########################################
# Source of FASTQ.GZ files.       #
# Should be .fq.gz or .fastq.gz files. #
########################################

INPUT-DIR: /media/root/working_disk/data_RNA_seqone_sample/big
TMP-DIR: tmp_big_dataset
OUT-DIR: output_big_dataset
SCRATCH: tmp

#########################
# CPU and memory params #
#########################
MACHINE:
    threads: 24
    threads_julia: 8
    memory_java: 8

##############
# References #
##############
REFERENCE: /media/root/ocean/Databases/HUMAN/hg38/GRCh38.primary_assembly.genome_ercc.fa
TRANSCRIPTS:
GFF3: 
GTF: /media/root/ocean/Databases/HUMAN/hg38/gencode.v28.primary_assembly_biotype_fix_rRNAsupl.annotation.gtf
###################
# Fastqc options. #
###################
FASTQC:
    kmer_size: 5   # [5]

############
# Trimming #
############
BBDUK:
    threads: 8
    ref: datasets/bbmap/two_short.fa
    ktrim: r
    k: 23
    mink: 11
    hdist: 1
    minlength: 10
    maxns: 1
    qtrim: r
    trimq: 15
    additional_params: "tpe tbo"

###############
# Subsampling #
###############
SUBSAMPLING:
    run: False
    subsample_to:

#############
# Alignment #
#############
MAPPING:
    STAR:
        threads: 24
        chimSegmentMin: 20
        additional_params: ""
