##########################################
# Program detects 3' ends of transcripts #
##########################################


########################################
# Destination of FASTQ.GZ files.       #
# Should be .fq.gz or .fastq.gz files. #
########################################

INPUT-DIR: /media/root/ocean/Databases/3EndD_testing_files/fastq #/media/root/ngs_nas3/testing_data_poly_A/
TMP-DIR: tmp
OUT-DIR: output
SCRATCH: tmp

#########################
# CPU and memory params #
#########################
MACHINE:
    threads: 24
    threads_julia: 8
    memory_java: 8

##############
# References #
##############
REFERENCE: /media/root/ocean/Databases/3EndD_testing_files/reference/GRCh38.primary_assembly.chr21.fa
polyA_ref: datasets/bbmap/polyA.fa
# TRANSCRIPTS: /media/root/ocean/Databases/3EndD_testing_files/reference/gencode.v28.transcripts.chr21.fa.gz
# GFF3: /media/root/ocean/Databases/3EndD_testing_files/reference/gencode.v28.primary_assembly.annotation_chr21.gff3
# GTF: /media/root/ocean/Databases/3EndD_testing_files/reference/gencode.v28.primary_assembly.annotation_chr21.gtf
TRANSCRIPTS: /media/root/ocean/Databases/hg38/gencode.v28.transcripts.fa.gz
GFF3: /media/root/ocean/Databases/hg38/gencode.v28.primary_assembly.annotation.gff3
GTF: /media/root/ocean/Databases/hg38/gencode.v28.primary_assembly.annotation.gtf
###################
# Fastqc options. #
###################
FASTQC:
    kmer_size: 5   # [5]

############
# Trimming #
############
BBDUK:
    threads: 8
    ref: datasets/bbmap/two_short.fa
    ktrim: r
    k: 23
    mink: 11
    hdist: 1
    minlength: 10
    maxns: 1
    qtrim: r
    trimq: 15
    additional_params: "tpe tbo"

###############
# Subsampling #
###############
SUBSAMPLING:
    run: False
    subsample_to:

#############
# Alignment #
#############
MAPPING:
    STAR:
        threads: 24
        chimSegmentMin: 20
        additional_params: ""
