##########################################
# Program detects 3' ends of transcripts #
##########################################


########################################
# Source of FASTQ.GZ files.       #
# Should be .fq.gz or .fastq.gz files. #
########################################

INPUT-DIR: datasets/small_dataset/small_fastqs
SAMPLES: HBR_100_Collibri_chr21small_A
LANE-REGEX: "L\\d\\d\\d_"
TMP-DIR: tmp_small_dataset
OUT-DIR: output_small_dataset
SCRATCH: tmp_small_dataset
BENCHMARKS: benchmarks

#########################
# CPU and memory params #
#########################
MACHINE:
    threads_julia: 12
    memory_java: 4
    threads_sambamba: 8

##############
# References #
##############
REFERENCE: datasets/small_dataset/references/GRCh38.primary_assembly.chr21_reduced.fa
TRANSCRIPTS:
GFF3: datasets/small_dataset/references/gencode.v28.primary_assembly.annotation_chr21_reduced.gff3
GTF: datasets/small_dataset/references/gencode.v28.primary_assembly.annotation_chr21_reduced.gtf
###################
# Fastqc options. #
###################
FASTQC:
    kmer_size: 5   # [5]

############
# Trimming #
############
BBDUK:
    threads: 8
    ref: datasets/bbmap/two_short.fa
    ktrim: r
    k: 23
    mink: 11
    hdist: 1
    minlength: 10
    maxns: 1
    qtrim: r
    trimq: 15
    additional_params: "tpe tbo"

###############
# Subsampling #
###############
SUBSAMPLING:
    threads: 4
    run: False
    subsample_to:

#############
# Alignment #
#############
MAPPING:
    STAR:
        threads: 24
        chimSegmentMin: 20
        additional_params: ""

####################
# Annotation of TS #
####################
ANNOTATE-TS:
    threads: 1
    k: 10
    m: 1
    mappingquality: 0              # [0] Only reads with greater than this mapping value will pass.
    strandness: "+"                  # [+] If R1 read is the same as a gene sequence: +; If R2 read is the same as a gene sequence: -;
    additional_params: "--cluster" # ["--cluster --verbose"]
